[package]
name = "julius"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libjulius-sys={path="../libjulius-sys"}
strum = "0.25"
strum_macros = "0.25"
anyhow = "1.0"
